---
- name: Install BIND9.
  ansible.builtin.apt:
    name:
      - bind9
      - bind9utils
      - bind9-doc
    state: present
  become: true

- name: Deploy BIND9 main configuration.
  ansible.builtin.template:
    src: "templates/named.conf.j2"
    dest: "/etc/bind/named.conf"
    owner: bind
    group: bind
    mode: 0644
  notify:
    - Check bind9 config
    - Restart bind9
  become: true

- name: Deploy BIND9 zone files per domain.
  ansible.builtin.template:
    src: "templates/ryangeary.dev.zone.j2"
    dest: "/etc/bind/ryangeary.dev.zone"
    owner: bind
    group: bind
    mode: 0644
  notify:
    - Check bind9 config
    - Restart bind9
  become: true

- name: Ensure BIND9 is running and enabled.
  ansible.builtin.service:
    name: bind9
    state: started
    enabled: true
  become: true
