---

- name: Install BIND9.
  ansible.builtin.apt:
    name:
      - bind9
      - bind9utils
      - bind9-doc
    state: present
  become: true

- name: Deploy BIND9 main configuration.
  ansible.builtin.template:
    src: "templates/named.conf.j2"
    dest: "/etc/bind/named.conf"
    owner: bind
    group: bind
    mode: 0644
  notify:
    - Check bind9 config
    - Restart bind9
  become: true

- name: Deploy BIND9 zone file.
  ansible.builtin.template:
    src: "templates/local_domain_name.zone.j2"
    dest: "/etc/bind/{{ local_domain_name }}.zone"
    owner: bind
    group: bind
    mode: 0644
  notify:
    - Check bind9 config
    - Restart bind9
  become: true

- name: Ensure BIND9 is running and enabled.
  ansible.builtin.service:
    name: bind9
    state: started
    enabled: true
  become: true

- name: Run handlers before testing to ensure any configuration changes are applied.
  ansible.builtin.meta: flush_handlers

- name: Test that truenas is resolvable from the bind9 server.
  ansible.builtin.command: "dig +short @{{ bind9_ip }} truenas.{{ local_domain_name }}"
  register: dig_truenas
  changed_when: false

- name: Assert that truenas resolves to the correct IP.
  ansible.builtin.assert:
    that:
      - dig_truenas.stdout == truenas_ip
    fail_msg: "DNS resolution for truenas.{{ local_domain_name }} did not return the expected IP address."

- name: Test that jellyfin is resolvable from the bind9 server.
  ansible.builtin.command: "dig +short @{{ bind9_ip }} jellyfin.{{ local_domain_name }}"
  register: dig_jellyfin
  changed_when: false

- name: Assert that jellyfin resolves to the correct IP.
  ansible.builtin.assert:
    that:
      - dig_jellyfin.stdout == "{{ansible_facts['hostname']}}.{{ local_domain_name }}.\n{{ ansible_facts['default_ipv4']['address'] }}"
    fail_msg: "DNS resolution for jellyfin.{{ local_domain_name }} did not return the expected IP address."

- name: Test that gl is resolvable from (through) the bind9 server.
  ansible.builtin.shell: "dig +short @{{ bind9_ip }} gl.{{ public_domain_name }} | wc -l"
  register: dig_gl
  changed_when: false

- name: Assert that gl resolves to the correct IP.
  ansible.builtin.assert:
    that:
      - dig_gl.stdout | int >= 1
    fail_msg: "DNS resolution for gl.{{ public_domain_name }} did not return the expected IP address. This public IP address may change from time to time, but as long as it resolves to some public ip address and gl is reachable, it is likely not an issue and this test may need updating. (Returned: {{ dig_gl.stdout }})"
