---
- name: Create per-service users and groups
  ansible.builtin.user:
    name: "{{ item.key }}"
    uid: "{{ item.value.uid }}"
    create_home: false
    shell: /usr/sbin/nologin
    state: present
  loop: "{{ service_accounts | dict2items }}"
  become: true

- name: Add login user to all service groups
  ansible.builtin.user:
    name: "{{ ansible_facts['env']['USER'] }}"
    groups: "{{ item.key }}"
    append: true # don't remove existing groups!
  loop: "{{ service_accounts | dict2items }}"
  become: true
