[env]
STATIC_DIR="{{config_root}}/static"
STACK_NAME="homelab"
_.file = '.env'

[tasks.build_site]
run = '''
#!/bin/bash
SITE=${1}
TS_DIR=${2:-${SITE}}
echo $SITE
cd $TS_DIR && pwd && npm run build && mkdir -p $STATIC_DIR/$SITE && rm -r $STATIC_DIR/$SITE/* && mv dist/* $STATIC_DIR/$SITE
'''

[tasks.build_container]
run = 'docker compose build -- '

[tasks.build_containers]
depends = [
    'build_container volume_backup',
]

[tasks.build]
depends = ['build_containers']

[tasks.push]
run = '''
#!/bin/sh
mise run build_container $1
docker compose push ${1}
'''

[tasks.push_all]
depends = [
    'push volume_backup',
]

[tasks.deploy]
depends = ['push_all']
run = '''
#!/bin/bash
docker stack config -c docker-compose.yml
docker stack config -c docker-compose.yml \
| yq 'del(.. | select(has("env_file")) | .env_file)' \
| ssh $MANAGER_HOST \
    'cd homelab && sudo docker stack deploy \
        --resolve-image=always \
        --detach=false \
        --with-registry-auth \
        -c - \
        homelab
    '
'''

[tasks.rollback]
run = "ssh $MANAGER_HOST 'docker service rollback $1'"

[tasks.config_view]
run = '''
#!/bin/bash
ssh $MANAGER_HOST "sudo docker config inspect $1" | jq '.[0].Spec.Data' | tr -d '\"' | base64 -d 
'''
