[env]
STATIC_DIR="{{config_root}}/static"

[tasks.build_www_site]
run = "cd www && npm run build && mkdir -p $STATIC_DIR/www && rm -r $STATIC_DIR/www/* && mv dist/* $STATIC_DIR/www"

[tasks.build_gl_site]
run = "cd gl/ts && npm run build && mkdir -p $STATIC_DIR/gl && rm -rf $STATIC_DIR/gl/* && mv dist/* $STATIC_DIR/gl"

[tasks.build_sites]
depends = ['build_www_site', 'build_gl_site']

[tasks.build_nginx_container]
depends = ['build_sites']
run = "docker compose build -- nginx"

[tasks.build_gl_container]
run = "docker compose build -- gl"

[tasks.build_smallweb_container]
run = "docker compose build -- smallweb"

[tasks.build_gl]
depends = ['build_gl_container', 'build_nginx_container', 'build_gl_site']

[tasks.build_containers]
depends = ['build_nginx_container', 'build_gl_container', 'build_smallweb_container']

[tasks.build]
depends = ['build_containers']

[tasks.push_gl]
run = "docker push ghcr.io/theryangeary/gl"
[tasks.push_nginx]
run = "docker push ghcr.io/theryangeary/nginx"
[tasks.push_smallweb]
run = "docker push ghcr.io/theryangeary/smallweb"
[tasks.push]
depends = ['push_gl', 'push_nginx', 'push_smallweb']

[tasks.deploy]
run = "docker stack config -c docker-compose.yml | ssh raspberrypi1.local 'cd homelab && docker stack deploy --with-registry-auth -c - homelab'"

