[env]
STATIC_DIR="{{config_root}}/static"
_.file = '.env'

[tasks.build_site]
run = '''
#!/bin/bash
SITE=${1}
TS_DIR=${2:-${SITE}}
echo $SITE
cd $TS_DIR && pwd && npm run build && mkdir -p $STATIC_DIR/$SITE && rm -r $STATIC_DIR/$SITE/* && mv dist/* $STATIC_DIR/$SITE
'''

[tasks.build_site_www]
depends = "build_site www"

[tasks.build_site_gl]
depends = "build_site gl gl/ts"

[tasks.build_sites]
depends = ['build_site_www', 'build_site_gl']

[tasks.build_container]
run = 'docker compose build -- '

[tasks.build_gl]
depends = ['build_container gl', 'build_container nginx', 'build_site_gl']

[tasks.build_containers]
depends = ['build_container nginx', 'build_container gl', 'build_container smallweb']

[tasks.build]
depends = ['build_containers']

[tasks.push]
run = '''
#!/bin/sh
mise run build_container $1
docker compose push ${1}
'''

[tasks.push_all]
depends = ['push gl', 'push nginx', 'push smallweb']

[tasks.deploy]
depends = ['push_all']
run = '''
#!/bin/bash
docker stack config -c docker-compose.yml
docker stack config -c docker-compose.yml \
| ssh raspberrypi1.local \
    'cd homelab && sudo docker stack deploy \
        --resolve-image=always \
        --detach=false \
        --with-registry-auth \
        -c - \
        homelab \
    '
'''

[tasks.rollback]
run = "ssh raspberrypi1.local 'docker service rollback $1'"

