[env]
STATIC_DIR="{{config_root}}/static"
VERSION="v1"
_.file = '.env'

[tasks.build_site]
run = '''
#!/bin/bash
SITE=${1}
TS_DIR=${2:-${SITE}}
echo $SITE
cd $TS_DIR && pwd && npm run build && mkdir -p $STATIC_DIR/$SITE && rm -r $STATIC_DIR/$SITE/* && mv dist/* $STATIC_DIR/$SITE
'''

[tasks.build_site_www]
depends = "build_site www"

[tasks.build_site_gl]
depends = "build_site gl gl/ts"

[tasks.build_sites]
depends = ['build_site_www', 'build_site_gl']

[tasks.build_container]
run = 'docker compose build -- '

[tasks.build_gl]
depends = ['build_container gl', 'build_container nginx', 'build_site_gl']

[tasks.build_containers]
depends = ['build_container nginx', 'build_container gl', 'build_container smallweb']

[tasks.build]
depends = ['build_containers']

[tasks.push]
run = '''
#!/bin/sh
docker push ghcr.io/theryangeary/${1}:${VERSION}
'''

[tasks.push_all]
depends = ['push gl', 'push nginx', 'push smallweb']

[tasks.deploy]
depends = ['push_all']
run = "docker stack config -c docker-compose.yml | ssh raspberrypi1.local 'cd homelab && docker stack deploy --with-registry-auth -c - homelab'"

[tasks.rollback]
run = "ssh raspberrypi1.local 'docker service rollback $1'"

[tasks.bump_version]
run = '''
#!/bin/bash
current_version=$(grep -o '^VERSION="v[0-9]\+' mise.toml | grep -o '[0-9]\+')
new_version=$(($current_version + 1))
sed -i '' -E "s/^VERSION=\"v[0-9]+\"/VERSION=\"v${new_version}\"/" mise.toml
'''
