http_port: 80
https_port: 443
dns_port: 53

# Service user and group definitions. these are used to do ACL for data directories mounted to the host
service_accounts:
  app:
    uid: 2000
    gid: 2000
  mtadisplay:
    uid: 2001
    gid: 2001
  gl:
    uid: 2002
    gid: 2002
  pathfinder:
    uid: 2003
    gid: 2003

tailscale_authkey_secret: "{{ lookup('bitwarden.secrets.lookup', '83613b90-a61d-4426-9bbe-b3ad00210afd') }}"

# bind9 ip should be the ip of the swarm manager from inventory
bind9_ip: "{{ hostvars[groups['swarm_managers'][0]]['ansible_facts']['default_ipv4']['address'] }}"

# for staging environment where bind9 is running on a different host than the swarm manager, we need to specify the staging bind9 ip separately
staging_inventory: "{{ lookup('file', '../environments/staging/inventory.yml') | from_yaml }}"
staging_bind9_ip: "{{ staging_inventory.all.hosts['labstg1'].ansible_host }}"

# internal docker services will be on the same ip as bind9 as long as homelab is a single host
internal_services_ip: "{{ bind9_ip }}"
truenas_ip: 192.168.0.228

local_domain_names:
  prod: "internal"
  stg: "staging.internal"

labprd1_ip_tailscale: 100.96.166.18
labstg1_ip_tailscale: 100.69.45.103
bind9_ip_tailscale: "{{ labprd1_ip_tailscale }}"
staging_bind9_ip_tailscale: "{{ labstg1_ip_tailscale }}"
internal_services_ip_tailscale: "{{ labprd1_ip_tailscale }}"
truenas_ip_tailscale: 100.64.49.52
