http_port: 80
security_ssh_port: 22766
security_ssh_allowed_users:
  - ryan
security_sudoers_passworded:
  - ryan
security_autoupdate_mail_to: "{{ lookup('env', 'MAILTO') }}"
firewall_flush_rules_and_chains: false
firewall_allowed_tcp_ports:
  - "{{ security_ssh_port }}"
  - "{{ http_port}}"
