http_port: 80

# Service user and group definitions. these are used to do ACL for data directories mounted to the host
service_accounts:
  app:
    uid: 2000
    gid: 2000
  mtadisplay:
    uid: 2001
    gid: 2001
  gl:
    uid: 2002
    gid: 2002
  pathfinder:
    uid: 2003
    gid: 2003

tailscale_authkey_secret: "{{ lookup('bitwarden.secrets.lookup', '83613b90-a61d-4426-9bbe-b3ad00210afd') }}"
