swarm_networks:
  cloudflare: "{{ stack_prefix | default('') }}cloudflare"
  services: "{{ stack_prefix | default('') }}services"
  services_internal: "{{ stack_prefix | default('') }}services_internal"
