---
- hosts: all
  become: true

  vars: 
    ghcr_token: "{{ lookup('bitwarden.secrets.lookup', 'a11c7900-ee0b-4c0d-8a38-b3ad00209876') }}"
    tailscale_authkey_secret: "{{ lookup('bitwarden.secrets.lookup', '83613b90-a61d-4426-9bbe-b3ad00210afd') }}"

  tasks:
    - name: Update apt package list
      ansible.builtin.apt: update_cache=yes cache_valid_time=3600

    - name: Ensure NTP is installed.
      ansible.builtin.apt: name=ntp state=present

    - name: Ensure NTP is running.
      ansible.builtin.service: name=ntp state=started enabled=yes
    
    # - name: Ensure pip is installed.
    #   ansible.builtin.apt: name=pip state=present

    # - name: Ensure jsondiff is installed (needed for compose).
    #   ansible.builtin.apt: name=python3-jsondiff state=present

    # - name: Ensure docker is installed.
    #   ansible.builtin.apt: name=docker.io state=present

    # - name: Ensure docker is running.
    #   ansible.builtin.service: name=docker state=started enabled=yes

    - name: Ensure tailscale is installed.
      include_role:
        name: artis3n.tailscale.machine
      vars:
        state: present
        tailscale_authkey: "{{ tailscale_authkey_secret }}"

    # - name: Ensure docker-compose is installed.
    #   ansible.builtin.apt: name=docker-compose state=present

    - name: Init a new swarm with default parameters
      community.docker.docker_swarm:
        state: present

    - name: Log in to ghcr.io
      community.docker.docker_login:
        registry: ghcr.io
        username: theryangeary
        password: "{{ ghcr_token }}"

    - name: Get git repository root directory path
      ansible.builtin.shell: git rev-parse --show-toplevel
      register: git_root
      delegate_to: localhost
      become: false

    - name: Create docker caddy config with hash as part of name.
      community.docker.docker_config:
        name: caddy_config
        state: present
        data: "{{ lookup('file', git_root.stdout + '/caddy/conf/Caddyfile') | b64encode }}"
        data_is_b64: true

    - name: Create docker authelia users database config
      community.docker.docker_config:
        name: authelia_users
        state: present
        data: "{{ lookup('file', git_root.stdout + '/authelia/config/users_database.yml') | b64encode }}"
        data_is_b64: true

    - name: Create docker authelia main configuration config
      community.docker.docker_config:
        name: authelia_config
        state: present
        data: "{{ lookup('file', git_root.stdout + '/authelia/config/configuration.yml') | b64encode }}"
        data_is_b64: true

    - name: Create homelab ftp password secret
      community.docker.docker_secret:
        name: homelab_ftp_password
        state: present
        data: "{{ lookup('bitwarden.secrets.lookup', '4967fb7b-9209-42f2-87a5-b3b1004608e1') | b64encode }}"
        data_is_b64: true

    - name: Create authelia jwt secret
      community.docker.docker_secret:
        name: authelia_jwt_secret
        state: present
        data: "{{ lookup('bitwarden.secrets.lookup', '4eec6601-9aef-47f2-aa2f-b3b1011fb2e3') | b64encode }}"
        data_is_b64: true

    - name: Create authelia session secret
      community.docker.docker_secret:
        name: authelia_session_secret
        state: present
        data: "{{ lookup('bitwarden.secrets.lookup', '1f98c85e-955a-4835-b275-b3b1011e4e2d') | b64encode }}"
        data_is_b64: true

    - name: Create authelia storage encryption key secret
      community.docker.docker_secret:
        name: authelia_storage_encryption_key
        state: present
        data: "{{ lookup('bitwarden.secrets.lookup', '4cca9e94-4946-4359-94c0-b3b1011ef4cd') | b64encode }}"
        data_is_b64: true

    - name: Create webhook secret
      community.docker.docker_secret:
        name: webhook_secret
        state: present
        data: "{{ lookup('bitwarden.secrets.lookup', '25e4555d-cdfe-4c6c-88c8-b3b10120c5ee') | b64encode }}"
        data_is_b64: true

    - name: Generate stack configuration locally
      ansible.builtin.shell: docker stack config -c {{ git_root.stdout }}/docker-compose.yml | yq 'del(.. | select(has("env_file")) | .env_file)'
      register: stack_config
      delegate_to: localhost
      become: false

    - name: Display generated stack configuration
      ansible.builtin.debug:
        var: stack_config

    - name: Deploy/Update Homelab Stack
      community.docker.docker_stack:
        state: present
        name: homelab
        compose:
          - "{{ stack_config.stdout | from_yaml }}"

    # - name: Undeploy Homelab Stack
    #   community.docker.docker_stack:
    #     state: absent 
    #     name: homelab

