- hosts: all
  vars_files:
    - vars/main.yml
    - vars/security.yml
    - vars/firewall.yml
  roles:
    - role: geerlingguy.security
      become: true
      tags: [host-setup, security]

    - role: geerlingguy.firewall
      become: true
      tags: [host-setup, security]

    - role: universal-packages
      tags: [host-setup, infrastructure]

    - role: create-service-users-groups
      tags: [host-setup, infrastructure]

    - role: install-docker
      tags: [docker, infrastructure]

    - role: artis3n.tailscale.machine
      tags: [tailscale, infrastructure]
      vars:
        state: present
        tailscale_authkey: "{{ tailscale_authkey_secret }}"
        tailscale_args: "--accept-dns=false"

- hosts: dns
  vars_files:
    - vars/main.yml
  roles:
    - role: bind9
      tags: [dns, bind9, services]

- hosts: swarm_managers
  vars_files:
    - vars/main.yml
  roles:
    - role: init-swarm
      tags: [swarm, infrastructure]

    - role: swarm-networks
      tags: [swarm, infrastructure]

    - role: service-cloudflared
      tags: [cloudflared, services]
      vars:
        service_account: "{{ service_accounts.app }}"

    - role: service-caddy
      tags: [caddy, services]
      vars:
        service_account: "{{ service_accounts.app }}"

    - role: service-caddy_internal
      tags: [caddy, services]
      vars:
        service_account: "{{ service_accounts.app }}"

    - role: service-authelia
      tags: [authelia, services]
      vars:
        service_account: "{{ service_accounts.app }}"

    - role: service-gl
      tags: [gl, services]
      vars:
        service_account: "{{ service_accounts.gl }}"

    - role: service-pathfinder
      tags: [pathfinder, services]
      vars:
        service_account: "{{ service_accounts.pathfinder }}"

    - role: service-mta-display
      tags: [mtadisplay, mta-display, services]
      vars:
        service_account: "{{ service_accounts.mtadisplay }}"

    - role: service-ntfy
      tags: [ntfy, services]

    - role: swarm-service
      tags: [vikunja, services]
      vars:
        swarm_service_name: "vikunja"
        swarm_service_environment: "{{ env }}"
        swarm_service_user: "{{ service_accounts.app }}"
        swarm_service_stack_config_template: "stacks/vikunja.yml.j2"
        swarm_service_create_data_directory: true
        swarm_service_data_directory_mode: '750'
        swarm_service_images:
          - "vikunja/vikunja:2.3"
        swarm_service_data_subdirectories:
          - name: "db"
            mode: '750'
          - name: "files"
            mode: '750'
