- hosts: all
  vars_files:
    - vars/main.yml
    - vars/security.yml
    - vars/firewall.yml
  roles:
    - role: geerlingguy.security
      become: true
      
    - role: geerlingguy.firewall
      become: true
    
    - role: universal-packages
      tags: [host-setup, infrastructure]

    - role: create-service-users-groups
      tags: [host-setup, infrastructure]

    - role: install-docker
      tags: [docker, infrastructure]

    - role: artis3n.tailscale.machine
      tags: [tailscale, infrastructure]
      vars:
        state: present
        tailscale_authkey: "{{ tailscale_authkey_secret }}"

- hosts: swarm_managers
  vars_files:
    - vars/main.yml
  roles:
    - role: init-swarm
      tags: [swarm, infrastructure]

    - role: swarm-networks
      tags: [swarm, infrastructure]

    - role: service-cloudflared
      tags: [cloudflared, services]
      vars:
        service_account: "{{ service_accounts.app }}"

    - role: service-caddy
      tags: [caddy, services]
      vars:
        service_account: "{{ service_accounts.app }}"

    - role: service-caddy_internal
      tags: [caddy, services]
      vars:
        service_account: "{{ service_accounts.app }}"

    - role: service-www
      tags: [www, services]

    - role: service-authelia
      tags: [authelia, services]
      vars:
        service_account: "{{ service_accounts.app }}"

    - role: service-gl
      tags: [gl, services]
      vars:
        service_account: "{{ service_accounts.gl }}"

    - role: service-pathfinder
      tags: [pathfinder, services]

    - role: service-mta-display
      tags: [mtadisplay, mta-display, services]
      vars:
        service_account: "{{ service_accounts.mtadisplay }}"

    - role: service-ntfy
      tags: [ntfy, services]
