--- 
- name: Create service config directory
  file:
    path: "/opt/stacks/caddy"
    state: directory

- name: Get git repository root directory path
  ansible.builtin.shell: git rev-parse --show-toplevel
  register: git_root
  delegate_to: localhost
  become: false

- name: Template caddy config file
  ansible.builtin.template:
    src: "{{ git_root.stdout }}/caddy/Caddyfile.j2"
    dest: /opt/stacks/caddy/Caddyfile
  delegate_to: localhost
  become: false

- name: Template stack file
  template:
    src: stacks/caddy.yml.j2
    dest: "/opt/stacks/caddy/stack.yml"
  register: stack_changed

- name: Deploy stack
  docker_stack:
    name: caddy
    compose:
      - "/opt/stacks/caddy/stack.yml"
    state: present
