--- 
- name: Create service config directory
  file:
    path: "/opt/stacks/{{ stack_prefix }}caddy"
    state: directory
  become: true

- name: Template caddy config file
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /opt/stacks/{{ stack_prefix }}caddy/Caddyfile
  register: caddy_config_result
  become: true

- name: Template stack file
  template:
    src: stack.yml.j2
    dest: "/opt/stacks/{{ stack_prefix }}caddy/stack.yml"
  register: stack_changed
  become: true

- name: Deploy stack
  docker_stack:
    name: "{{ stack_prefix }}caddy"
    compose:
      - "/opt/stacks/{{ stack_prefix }}caddy/stack.yml"
    state: present
  become: true

- name: Send signal to force caddy to reload config
  community.docker.docker_swarm_service:
    name: "{{ stack_prefix }}caddy_caddy"
    force_update: true
    image: "caddy:{{ caddy_version }}"
  become: true
