storage:
  local:
    path: '/config/db.sqlite3'

log:
  level: debug

# session:
#   expiration: '1m'
#   cookies:
#     - domain: 'ryangeary.dev'
#       authelia_url: 'https://auth.ryangeary.dev'
#       default_redirection_url: 'https://www.ryangeary.dev'

session:
  expiration: '1m'
  name: authelia_session
  cookies:
    - domain: 'ryangeary.localhost'
      authelia_url: 'https://auth.ryangeary.localhost'
      default_redirection_url: 'https://www.ryangeary.localhost'

server:
  address: 'tcp://:9091'
  # tls:
  #   certificate: '/config/certs/cert.pem'
  #   key: '/config/certs/key.pem'
  endpoints:
    authz:
      # auth-request:
      #   implementation: 'AuthRequest'
      forward-auth:
        implementation: 'ForwardAuth'

authentication_backend:
  password_change:
    disable: true
  password_reset:
    disable: true
  file:
    path: '/config/users_database.yml'

access_control:
  default_policy: 'one_factor'
  rules:
    - domain: 'auth.ryangeary.localhost'
      policy: bypass

notifier:
  disable_startup_check: true
  filesystem:
    filename: '/config/notification.txt'
