---
- name: Update apt package list
  ansible.builtin.apt: 
    update_cache: yes
    cache_valid_time: 86400
  become: true

- name: Ensure timesyncd is installed.
  ansible.builtin.apt: name=systemd-timesyncd state=present
  become: true

- name: Ensure timesyncd is running.
  ansible.builtin.service: name=systemd-timesyncd state=started enabled=yes

- name: Ensure sqlite is installed for debugging.
  ansible.builtin.apt: name=sqlite3 state=present
  become: true

- name: Ensure tailscale is installed.
  include_role:
    name: artis3n.tailscale.machine
  vars:
    state: present
    tailscale_authkey: "{{ tailscale_authkey_secret }}"
