all:
  hosts:
    labprd1:
      ansible_host: 192.168.0.238
      ip_address: 192.168.0.238
      ansible_port: "{{ ssh_port }}"
      ansible_become_password: "{{ become_password }}"
  children:
    swarm_managers:
      hosts:
        labprd1:
    dns:
      hosts:
        labprd1:
